Send notification mail
devnotcom/devnot-mentor-back-end pull request #44
Opened 2021-08-06 22:13 UTC by bariscanyilmaz

#17 Numaralı issue için çözüm

2021-08-31 23:08 UTC, halilkocaoz commented
Merhaba @bariscanyilmaz. Geç dönüş yapıldığı için özür dilerim, conflictler ile ilgilenebilir misin?

2021-09-01 15:49 UTC, halilkocaoz requested changes
İşaretlediğim metotlar ApplicationService altına taşınmıştı, conflictlere göz atarken göreceğini düşünmüştüm, bunları göz önünde bulundurarak tekrar düzenleyebilir misin?

2021-09-01 15:49 UTC, halilkocaoz commented on Devnot.Mentor.Api/Services/MenteeService.cs
> +        }
[CreateApplicationAsync](https://github.com/devnotcom/devnot-mentor-back-end/blob/master/Devnot.Mentor.Api/Services/ApplicationService.cs#L123)

2021-09-01 15:49 UTC, halilkocaoz commented on Devnot.Mentor.Api/Services/MentorService.cs
> +        }
[ApproveWaitingApplicationByIdAsync](https://github.com/devnotcom/devnot-mentor-back-end/blob/master/Devnot.Mentor.Api/Services/ApplicationService.cs#L48)

2021-09-01 15:49 UTC, halilkocaoz commented on Devnot.Mentor.Api/Services/MentorService.cs
> +
[RejectWaitingApplicationByIdAsync](https://github.com/devnotcom/devnot-mentor-back-end/blob/master/Devnot.Mentor.Api/Services/ApplicationService.cs#L90)

2021-09-01 15:49 UTC, halilkocaoz commented on Devnot.Mentor.Api/Services/MentorService.cs
> +        }
[isCountOfContinuingMentorshipsGreaterThanOREqualToMaxCountForMentee](https://github.com/devnotcom/devnot-mentor-back-end/blob/master/Devnot.Mentor.Api/Services/ApplicationService.cs#L111)

[isCountOfContinuingMentorshipsGreaterThanOREqualToMaxCountForMentor](https://github.com/devnotcom/devnot-mentor-back-end/blob/master/Devnot.Mentor.Api/Services/ApplicationService.cs#L117)

2021-09-01 18:23 UTC, bariscanyilmaz commented
Merhaba @halilkocaoz, özür dilerim dikkat etmemişim. Gerekli değişiklikleri yaptım.
* Bildirim maili ApplicationService altında gönderilmekte.
* MentorService ve MenteeService altındaki ApplicationService'e taşınan metotlar silindi.

2021-09-01 19:32 UTC, merged